version: '3'

networks:
  movies_network:
    driver: bridge

services:
  postgres:
    image: postgres:13
    container_name: postgres_movies
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - movies_network

  movies_web:
    platform: linux/amd64
    build: app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - movies_network
    volumes:
    - static_volume:/opt/app/static
    - media_volume:/opt/app/media

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
    depends_on:
      - movies_web
    ports:
      - "80:80"
    networks:
      - movies_network

volumes:
 static_volume:
 media_volume:
 postgres_data:



